// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Config = { groupSongsInFolder: boolean, downloadFolder: string, deezerMergeTracks: boolean, youtubeFormat: "mp3" | "webm" | "wav" | "ogg", youtubeSplitChapters: boolean, };
