// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Event = { "type": "waiting", "payload": string } | { "type": "start", "payload": string } | { "type": "finish", "payload": string } | { "type": "download_error", "payload": [string, string] } | { "type": "album_track_complete", "payload": [string, number] } | { "type": "album_track_error", "payload": [string, number, string] };
