// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Album } from "./Album";
import type { Song } from "./Song";

export type Item = { "type": "DeezerAlbum", album: Album, mergeTracks: boolean, } | { "type": "DeezerTrack", track: Song, } | { "type": "YoutubeVideo", video: Song, splitByChapters: boolean | null, } | { "type": "YoutubePlaylist", playlist: Album, };
