// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Album } from "./Album";
import type { Song } from "./Song";

export type Item = { "type": "DeezerAlbum" } & Album | { "type": "DeezerTrack" } & Song | { "type": "YoutubeVideo" } & Song | { "type": "YoutubePlaylist" } & Album;
