// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Song } from "./models\\Song";

export type Event = { "Waiting": Song } | { "Start": Song } | { "Finish": Song } | { "DownloadError": Song } | { "AddToQueue": Song } | { "RemoveFromQueue": Song };