// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Song } from "./models\\Song";

export type Event = { "waiting": Song } | { "start": Song } | { "finish": Song } | { "download_error": Song } | { "add_to_queue": Song } | { "remove_from_queue": Song };